dist: xenial
language: c

compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libtalloc-dev uthash-dev libarchive-dev gdb strace realpath libprotobuf-c-dev libattr1-dev

script: make -C src
